version: '2'
services:

  app:
    container_name: breizhtival_app
    restart: always
    build:
      context: ./
      dockerfile: dockerfile
      args:
        - DOCKER_APP_PORT=80
        - DOCKER_MONGO_HOST=mongo
    image: breizhtival:latest
    ports:
      - 80:80
    networks:
      - nodejs

  mongo:
    container_name: breizhtival_mongo
    image: mongo:4.2
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootmongo
      MONGO_INITDB_DATABASE: app
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - 27017:27017
    networks:
      - nodejs

  mongo-viewer:
    container_name: breizhtival_mongo-viewer
    image: mongo-express
    restart: always
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: rootmongo
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 0
      ME_CONFIG_MONGODB_AUTH_DATABASE: app
      ME_CONFIG_MONGODB_AUTH_USERNAME: app
      ME_CONFIG_MONGODB_AUTH_PASSWORD: appmongo
    ports:
      - 8082:8081
    networks:
      - nodejs

networks:
  nodejs:
    driver: bridge